config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    resources :favorite, only: [] do
      collection do
        get :recipes
      end
    end
  end

  resources :recipes do
    resources :favorite, only: [] do
      collection do
        post :toggle
      end
    end
  end

  root 'recipes#index'

  resources :search, only: [] do
    collection do
      get :recipes
    end
  end

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  include PgSearch
  has_many :favorites

  # multisearchable :against => [:name, :ingredients, :time]
  pg_search_scope :whose_name_starts_with,
    :against => [:name, :ingredients, :time],
    :using => {
      :tsearch => {:prefix => true}
    }

  def favorited_by( user )
    favorites.where(user_id: user.id).present?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :favorites

  def favorite( recipe )
    favorites.where(recipe: recipe).first_or_create
  end

  def unfavorite( recipe )
    favorites.where(recipe: recipe).destroy_all
  end

  def admin?
    roles == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception unless Rails.env.test?

  def not_found
    render 'layouts/404'
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  include Gaffe::Errors

  # Make sure anonymous users can see the page
  skip_before_filter :authenticate_user!

  # Override 'error' layout
  layout 'application'

  # Render the correct template based on the exception “standard” code.
  # Eg. For a 404 error, the `errors/not_found` template will be rendered.
  def show
    # Here, the `@exception` variable contains the original raised error
    render "layouts/404", status: @status_code
  end
end

app/controllers/favorite_controller.rb
class FavoriteController < ApplicationController
  def toggle
    return unless user_signed_in?
    find_and_toggle_recipe
    render template: 'recipes/toggle.js.erb'
  end

  def recipes
    return unless user_signed_in?
    @recipes = []
    if favorites = find_user_recipes
      favorites.each do |f|
        @recipes << Recipe.find(f.recipe_id)
      end
      render partial: 'recipes/favorites.js.erb'
    else
      render :nothing => true
    end
  end

  private

  def find_and_toggle_recipe
    @recipe = find_recipe
    if @recipe.favorited_by current_user
      current_user.unfavorite @recipe
    else
      current_user.favorite @recipe
    end
  end

  def find_recipe
    if id = params[:recipe_id].presence
      Recipe.find id
    end
  end

  def find_user_recipes
    if id = params[:user_id].presence
      current_user.favorites
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all.page params[:page]
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :time, :ingredients, :description, :image_url)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def recipes
    @recipes = Recipe.whose_name_starts_with(params[:keywords])
    @recipes = @recipes.page(params[:page]).per(2)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def ingredients_format
    if @recipe.ingredients.present?
      a =  @recipe.ingredients.split(',')
      string = '<ul>'
      a.each do |i|
        string = string + "<li>#{i}</li>"
      end
      string = string + "</ul>"
    end
  end

  def toggle_xhr(recipe)
    if current_user
      if recipe.favorited_by current_user
        'Unfavorite'
      else
        'Favorite'
      end
    end
  end
end

app/views/favorite/recipes.html.erb
<h3> Favorite Recipes: </h3>
<%= render partial: 'layouts/recipes' %>

app/views/layouts/404.html.erb
<h3>Sorry this recipe doesn't exist or may have been removed!<h3>

app/views/layouts/_recipes.html.erb
<% if @recipes.empty? %>
  <% if controller_name == 'favorite' %>
    <h3>Sorry you don't currently have any favorited recipes</h3>
  <% else %>
    <h3>Sorry we currently have no recipes for you</h3>
  <% end %>

<% else %>
<table border="1" class ="recipe-index">
  <thead>
    <tr>
      <th>Name</th>
      <th>Ingredients</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr class='recipe'>
        <td><%= recipe.name %></td>
        <td><%= recipe.ingredients %></td>
        <td><%= recipe.time %></td>
        <td><%= link_to 'Show', recipe %></td>
        <% if current_user && current_user.admin? %>
          <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
          <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% end  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cookbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'search/search_navigation' %>
<%= link_to 'Log in', new_user_session_path unless user_signed_in? %>
<%= link_to 'Sign up', new_user_registration_path unless user_signed_in?%>
<% if user_signed_in? %>
  <div><%= current_user.email %>
  <%= link_to 'Log out', destroy_user_session_path, :method => :delete %>
</div>
<% end %>
<%= yield %>

</body>
</html>

app/views/recipes/_favorites.js.erb
$(".recipe-index").html("<%= escape_javascript(render 'layouts/recipes') %>")

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% @recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br>
    <%= f.text_field :ingredients %>
    <%= "(separate ingredients with comma)" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1 class="title-func">Cookbook</h1>
<%= form_tag recipes_search_index_path, method: 'get', html: {role: 'search', class: 'Search'} do %>
  <input id="keywords" name="keywords" type="search" class="Search-input" placeholder="search here" value="<%= params[:keywords] %>">
  <button class="Search-btn" value="Search">
    <i class="Icon Icon--magnifier Icon--xxlg u-mt10" aria-hidden="true">
      <span class="u-textHide">Go</span>
    </i>
  </button>
<% end %>
<%= render partial: 'layouts/recipes' %>
<%= link_to 'New Recipe', new_recipe_path if current_user && current_user.admin?%>
<%= link_to 'Favorites', recipes_user_favorite_index_path(current_user), remote: true if current_user %>
<%= paginate @recipes %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>
<% if current_user%>
  <%= link_to toggle_xhr(@recipe), toggle_recipe_favorite_index_path(@recipe), method: 'post', remote: true, id: 'favorite_link' %>
<% end %>
<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Time:</strong>
  <%= @recipe.time %>
</p>
<p>
  <strong>Ingredients:</strong>
    <%= raw ingredients_format %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<p>
  <%= image_tag  @recipe.image_url %>
</p>

app/views/recipes/toggle.js.erb
$("#favorite_link").text("<%= toggle_xhr(@recipe) %>");

app/views/search/_search_navigation.html.erb
<%= link_to "Home", root_path %>

app/views/search/recipes.html.erb
<h3> Recipes for: <%= params[:keywords] %> </h3>
<% if @recipes.empty?%>
  <h4>No results<h4>
<% else %>
  <%= render partial: 'layouts/recipes' %>
<% end %>

<%= paginate @recipes %>